import type { RunDetail } from "./types";

const now = new Date();
const createdAt = new Date(now.getTime() - 120_000).toISOString();
const t = (offset: number) =>
  new Date(now.getTime() - 120_000 + offset).toISOString();

export const DEMO_RUN: RunDetail = {
  id: "demo-run-01",
  status: "fail",
  source_type: "remote",
  bundle_hash: null,
  created_at: createdAt,
  started_at: new Date(now.getTime() - 110_000).toISOString(),
  finished_at: new Date(now.getTime() - 10_000).toISOString(),
  duration_ms: 100_000,
  error_text: null,
  test_spec_json: {
    conversation_tests: [
      {
        name: "Appointment Booking",
        caller_prompt:
          "I need to book an appointment for tomorrow at 2pm for a haircut",
        max_turns: 8,
      },
      {
        name: "Refund Request",
        caller_prompt:
          "I want a refund for my order #12345, the product arrived damaged",
        max_turns: 10,
        persona: {
          emotion: "frustrated",
          pace: "fast",
          cooperation: "reluctant",
        },
      },
    ],
  },
  aggregate_json: {
    conversation_tests: { total: 2, passed: 1, failed: 1 },
    total_duration_ms: 100_000,
  },
  is_baseline: false,
  scenarios: [
    // --- Conversation Tests ---
    {
      id: "demo-conv-01",
      run_id: "demo-run-01",
      name: "Appointment Booking",
      status: "completed",
      test_type: "conversation",
      metrics_json: {
        name: "Appointment Booking",
        caller_prompt:
          "I need to book an appointment for tomorrow at 2pm for a haircut",
        status: "completed",
        transcript: [
          {
            role: "agent" as const,
            text: "Hi there! Welcome to StyleCuts. How can I help you today?",
            timestamp_ms: 0,
            ttfb_ms: 480,
            audio_duration_ms: 2800,
            stt_confidence: 0.96,
          },
          {
            role: "caller" as const,
            text: "Hi, I'd like to book an appointment for tomorrow at 2pm for a haircut please.",
            timestamp_ms: 3200,
            audio_duration_ms: 3500,
            stt_confidence: 0.94,
          },
          {
            role: "agent" as const,
            text: "Of course! I'd be happy to help you book a haircut for tomorrow at 2pm. Could I get your name please?",
            timestamp_ms: 7100,
            ttfb_ms: 550,
            audio_duration_ms: 4200,
            stt_confidence: 0.97,
          },
          {
            role: "caller" as const,
            text: "Sure, it's Sarah Mitchell.",
            timestamp_ms: 11800,
            audio_duration_ms: 1600,
            stt_confidence: 0.92,
          },
          {
            role: "agent" as const,
            text: "Great, Sarah! I've booked you in for a haircut tomorrow at 2pm. Your confirmation number is SC-4821. Is there anything else I can help with?",
            timestamp_ms: 13900,
            ttfb_ms: 710,
            audio_duration_ms: 5800,
            stt_confidence: 0.98,
          },
        ],
        observed_tool_calls: [
          {
            name: "book_appointment",
            arguments: {
              customer_name: "Sarah Mitchell",
              date: "2026-02-27",
              time: "14:00",
              service: "haircut",
            },
            result: { confirmation_id: "SC-4821", status: "confirmed" },
            successful: true,
            timestamp_ms: 13400,
            latency_ms: 230,
          },
        ],
        audio_action_results: [
          {
            at_turn: 3,
            action: "latency_check",
            metrics: { ttfb_ms: 550, ttfw_ms: 720 },
            transcriptions: {
              agent_response: "Of course! I'd be happy to help you book a haircut for tomorrow at 2pm.",
            },
          },
        ],
        duration_ms: 18200,
        metrics: {
          mean_ttfb_ms: 580,
          latency: {
            ttfb_per_turn_ms: [480, 550, 710],
            p50_ttfb_ms: 550,
            p90_ttfb_ms: 710,
            p95_ttfb_ms: 710,
            p99_ttfb_ms: 710,
            first_turn_ttfb_ms: 480,
            total_silence_ms: 1200,
            mean_turn_gap_ms: 240,
          },
          transcript: {
            wer: 0.08,
            repetition_score: 0.02,
            reprompt_count: 0,
            filler_word_rate: 1,
            words_per_minute: 145,
            vocabulary_diversity: 0.82,
          },
          tool_calls: {
            total: 1,
            successful: 1,
            failed: 0,
            mean_latency_ms: 230,
            names: ["book_appointment"],
          },
          audio_analysis: {
            agent_speech_ratio: 0.72,
            talk_ratio_vad: 0.38,
            longest_monologue_ms: 5800,
            silence_gaps_over_2s: 0,
            total_internal_silence_ms: 800,
            per_turn_speech_segments: [1, 1, 1],
            per_turn_internal_silence_ms: [200, 300, 300],
            mean_agent_speech_segment_ms: 4267,
          },
        },
      },
      trace_json: [],
      created_at: createdAt,
    },
    {
      id: "demo-conv-02",
      run_id: "demo-run-01",
      name: "Refund Request",
      status: "completed",
      test_type: "conversation",
      metrics_json: {
        name: "Refund Request",
        caller_prompt:
          "I want a refund for my order #12345, the product arrived damaged",
        status: "completed",
        transcript: [
          {
            role: "agent" as const,
            text: "Thank you for calling customer support. How can I assist you today?",
            timestamp_ms: 0,
            ttfb_ms: 620,
            audio_duration_ms: 3100,
            stt_confidence: 0.95,
          },
          {
            role: "caller" as const,
            text: "Hi, I received my order number 12345 and the product is damaged. I'd like a refund.",
            timestamp_ms: 3600,
            audio_duration_ms: 4200,
            stt_confidence: 0.93,
          },
          {
            role: "agent" as const,
            text: "I'm sorry to hear that. Let me look up your order. Yes, I can see order 12345. I can process a full refund for you right away.",
            timestamp_ms: 8400,
            ttfb_ms: 890,
            audio_duration_ms: 5600,
            stt_confidence: 0.96,
          },
          {
            role: "caller" as const,
            text: "Okay, how long will that take?",
            timestamp_ms: 14500,
            audio_duration_ms: 1800,
            stt_confidence: 0.91,
          },
          {
            role: "agent" as const,
            text: "The refund will be processed within 3 to 5 business days and will appear on your original payment method.",
            timestamp_ms: 16800,
            ttfb_ms: 1050,
            audio_duration_ms: 4800,
            stt_confidence: 0.97,
          },
          {
            role: "caller" as const,
            text: "And can I also get a replacement sent out?",
            timestamp_ms: 22100,
            audio_duration_ms: 2200,
            stt_confidence: 0.94,
          },
          {
            role: "agent" as const,
            text: "Sure, I'll send a replacement right away. Is there anything else I can help with?",
            timestamp_ms: 24800,
            ttfb_ms: 1240,
            audio_duration_ms: 3800,
            stt_confidence: 0.95,
          },
        ],
        duration_ms: 28600,
        metrics: {
          mean_ttfb_ms: 950,
          latency: {
            ttfb_per_turn_ms: [620, 890, 1050, 1240],
            p50_ttfb_ms: 970,
            p90_ttfb_ms: 1240,
            p95_ttfb_ms: 1240,
            p99_ttfb_ms: 1240,
            first_turn_ttfb_ms: 620,
            total_silence_ms: 2800,
            mean_turn_gap_ms: 380,
          },
          transcript: {
            wer: 0.12,
            repetition_score: 0.05,
            reprompt_count: 0,
            filler_word_rate: 3,
            words_per_minute: 132,
            vocabulary_diversity: 0.74,
          },
        },
      },
      trace_json: [],
      created_at: createdAt,
    },

  ],
  artifacts: [],
  events: [
    {
      id: "demo-evt-01",
      run_id: "demo-run-01",
      event_type: "health_check_passed",
      message: "Health check passed -- agent is reachable",
      metadata_json: null,
      created_at: t(0),
    },
    {
      id: "demo-evt-02",
      run_id: "demo-run-01",
      event_type: "test_completed",
      message: "Audio Quality probe completed",
      metadata_json: {
        test_name: "audio_quality",
        test_type: "audio",
        status: "completed",
        duration_ms: 7400,
        completed: 1,
        total: 9,
      },
      created_at: t(5000),
    },
    {
      id: "demo-evt-03",
      run_id: "demo-run-01",
      event_type: "test_completed",
      message: "Latency probe completed",
      metadata_json: {
        test_name: "latency",
        test_type: "audio",
        status: "completed",
        duration_ms: 8500,
        completed: 2,
        total: 9,
      },
      created_at: t(15000),
    },
    {
      id: "demo-evt-04",
      run_id: "demo-run-01",
      event_type: "test_completed",
      message: "Echo Detection probe completed",
      metadata_json: {
        test_name: "echo",
        test_type: "audio",
        status: "completed",
        duration_ms: 3200,
        completed: 3,
        total: 9,
      },
      created_at: t(20000),
    },
    {
      id: "demo-evt-05",
      run_id: "demo-run-01",
      event_type: "test_completed",
      message: "Appointment Booking completed",
      metadata_json: {
        test_name: "Appointment Booking",
        test_type: "conversation",
        status: "pass",
        duration_ms: 18200,
        completed: 4,
        total: 9,
      },
      created_at: t(45000),
    },
    {
      id: "demo-evt-06",
      run_id: "demo-run-01",
      event_type: "test_completed",
      message: "Refund Request completed",
      metadata_json: {
        test_name: "Refund Request",
        test_type: "conversation",
        status: "fail",
        duration_ms: 28600,
        completed: 5,
        total: 9,
      },
      created_at: t(70000),
    },
    {
      id: "demo-evt-07",
      run_id: "demo-run-01",
      event_type: "run_complete",
      message: "Run finished -- 1 failure detected",
      metadata_json: { status: "fail", completed: 5, total: 5 },
      created_at: t(90000),
    },
  ],
};
